package io.bluetape4k.exposed.clickhouse.support

import java.lang.reflect.InvocationTargetException
import java.lang.reflect.Method
import java.lang.reflect.Proxy
import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.ResultSet
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicInteger

/** 실제 JDBC 호출에 위임하면서 활성 자원과 유한 테스트 gate를 관측합니다. */
internal class JdbcObservation {
    val connections = AtomicInteger()
    val statements = AtomicInteger()
    val results = AtomicInteger()
    val executed = AtomicInteger()
    val queryTimeouts = AtomicInteger()
    val cancels = AtomicInteger()
    val next = AtomicInteger()
    var beforeNext: () -> Unit = {}
    var afterNext: () -> Unit = {}
    var resultCloseFailure: Throwable? = null
    var statementCloseFailure: Throwable? = null
    var connectionCloseFailure: Throwable? = null
}

internal class TrackingClickHouseConnection(
    private val delegate: Connection,
    private val observed: JdbcObservation,
): Connection by delegate {
    private val closed = AtomicBoolean()
    private val markers = mutableMapOf<String, String>()

    init {
        observed.connections.incrementAndGet()
    }

    override fun setClientInfo(name: String, value: String?) {
        if (value == null) markers.remove(name) else markers[name] = value
    }

    override fun getClientInfo(name: String): String? = markers[name]

    override fun close() {
        if (!closed.compareAndSet(false, true)) return
        try {
            delegate.close()
        } finally {
            observed.connections.decrementAndGet()
        }
        observed.connectionCloseFailure?.let { throw it }
    }

    override fun prepareStatement(sql: String): PreparedStatement = trackStatement(delegate.prepareStatement(sql))

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement = prepareStatement(sql)

    override fun prepareStatement(sql: String, columnIndexes: IntArray): PreparedStatement = prepareStatement(sql)

    override fun prepareStatement(sql: String, columnNames: Array<out String>): PreparedStatement =
        prepareStatement(sql)

    override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement =
        prepareStatement(sql)

    override fun prepareStatement(
        sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int,
    ): PreparedStatement = prepareStatement(sql)

    private fun trackStatement(statement: PreparedStatement): PreparedStatement {
        observed.statements.incrementAndGet()
        val closed = AtomicBoolean()
        return Proxy.newProxyInstance(
            PreparedStatement::class.java.classLoader, arrayOf(PreparedStatement::class.java),
        ) { _, method, args ->
            when (method.name) {
                "executeQuery" -> {
                    observed.executed.incrementAndGet()
                    trackResult(invokeJdbc(statement, method, args) as ResultSet)
                }
                "setQueryTimeout" -> {
                    observed.queryTimeouts.incrementAndGet()
                    invokeJdbc(statement, method, args)
                }
                "cancel" -> {
                    observed.cancels.incrementAndGet()
                    invokeJdbc(statement, method, args)
                }
                "close" -> {
                    if (closed.compareAndSet(false, true)) {
                        try {
                            invokeJdbc(statement, method, args)
                        } finally {
                            observed.statements.decrementAndGet()
                        }
                        observed.statementCloseFailure?.let { throw it }
                    }
                    null
                }
                else -> invokeJdbc(statement, method, args)
            }
        } as PreparedStatement
    }

    private fun trackResult(result: ResultSet): ResultSet {
        observed.results.incrementAndGet()
        val closed = AtomicBoolean()
        return Proxy.newProxyInstance(
            ResultSet::class.java.classLoader, arrayOf(ResultSet::class.java),
        ) { _, method, args ->
            when (method.name) {
                "next" -> {
                    observed.beforeNext()
                    val value = invokeJdbc(result, method, args)
                    observed.next.incrementAndGet()
                    observed.afterNext()
                    value
                }
                "close" -> {
                    if (closed.compareAndSet(false, true)) {
                        try {
                            invokeJdbc(result, method, args)
                        } finally {
                            observed.results.decrementAndGet()
                        }
                        observed.resultCloseFailure?.let { throw it }
                    }
                    null
                }
                else -> invokeJdbc(result, method, args)
            }
        } as ResultSet
    }
}

private fun invokeJdbc(target: Any, method: Method, args: Array<out Any?>?): Any? = try {
    method.invoke(target, *(args ?: emptyArray()))
} catch (caught: InvocationTargetException) {
    throw caught.targetException
}
