package io.bluetape4k.exposed.starrocks

import java.sql.Connection
import java.sql.PreparedStatement

/**
 * JDBC connection adapter for StarRocks Connector/J.
 *
 * The wrapper keeps Exposed's transaction adapter in autocommit mode and
 * delegates generated-key `prepareStatement` overloads to the plain SQL
 * overload. This matches the narrow OLAP module contract: statements are
 * executed independently and rollback is not used as a durability guarantee.
 */
@Suppress("JavaDefaultMethodsNotOverriddenByDelegation")
internal class StarRocksConnectionWrapper(
    private val conn: Connection,
): Connection by conn {

    init {
        conn.autoCommit = true
    }

    override fun getAutoCommit(): Boolean = true

    override fun setAutoCommit(autoCommit: Boolean) {
        if (!conn.autoCommit) conn.autoCommit = true
    }

    override fun commit() {
        // no-op: StarRocks smoke scope is autocommit-only.
    }

    override fun rollback() {
        // no-op: StarRocks smoke scope is autocommit-only.
    }

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement =
        conn.prepareStatement(sql)

    override fun prepareStatement(sql: String, columnIndexes: IntArray): PreparedStatement =
        conn.prepareStatement(sql)

    override fun prepareStatement(sql: String, columnNames: Array<out String>): PreparedStatement =
        conn.prepareStatement(sql)
}
