package io.bluetape4k.exposed.starrocks

import java.sql.Connection
import java.sql.PreparedStatement

/**
 * StarRocks Connector/J용 JDBC connection adapter입니다.
 *
 * 이 wrapper는 Exposed transaction adapter를 autocommit 모드로 유지하고 generated-key
 * `prepareStatement` overload를 일반 SQL overload에 위임합니다. statement를 독립적으로 실행하고
 * rollback을 durability 보장으로 사용하지 않는 제한된 OLAP 모듈 계약에 맞춥니다.
 */
@Suppress("JavaDefaultMethodsNotOverriddenByDelegation")
internal class StarRocksConnectionWrapper(
    private val conn: Connection,
): Connection by conn {

    init {
        conn.autoCommit = true
    }

    override fun getAutoCommit(): Boolean = true

    override fun setAutoCommit(autoCommit: Boolean) {
        if (!conn.autoCommit) conn.autoCommit = true
    }

    override fun commit() {
        // no-op: StarRocks smoke scope is autocommit-only.
    }

    override fun rollback() {
        // no-op: StarRocks smoke scope is autocommit-only.
    }

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement =
        conn.prepareStatement(sql)

    override fun prepareStatement(sql: String, columnIndexes: IntArray): PreparedStatement =
        conn.prepareStatement(sql)

    override fun prepareStatement(sql: String, columnNames: Array<out String>): PreparedStatement =
        conn.prepareStatement(sql)
}
